{% set name = "poetry-dynamic-versioning-plugin" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-dynamic-versioning-plugin-{{ version }}.tar.gz
  sha256: c918c5c0f582a4a9e354f22a919ead838b8e34cd854edc06dddb27ad8e9a2f6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - dunamai >=1.12.0,<2.0.0
    - jinja2 >=2.11.1,<4
    - poetry >=1.2.0b1,<2.0.0
    - python >=3.7
    - tomlkit >=0.4

test:
  imports:
    - poetry_dynamic_versioning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mtkennerly/poetry-dynamic-versioning
  summary: Plugin for Poetry to enable dynamic versioning based on VCS tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
